name: Build and Deploy to Google Cloud Storage

on:
  push:
    branches:
      - master
env:
  GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup - gcloud / gsutil
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCS_SA_KEY }}
          project_id: ${{ secrets.GCS_PROJECT }}
          export_default_credentials: true
      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: AndrewSelvia/scaladown
          path: scaladown
      - name: Run it
        run: |-
          pwd
          ls
          cd scaladown
          pwd
          ls
          /usr/bin/sbt "run .. /tmp/junk"
          pwd
          ls
          gsutil -m rm -r gs://$GCS_BUCKET/*
          pwd
          ls
          gsutil -m rsync -R /tmp/junk gs://$GCS_BUCKET